### ISSUE TITLE
make wiki

### ISSUE THREAD

**Issue by ohmpsy** [handsomekiwi/windbot-for-using#1]
Hello, make a wiki translation how to create ai.

**Comment by handsomekiwi** [comment]
https://github.com/IceYGO/windbot/wiki/%E5%A6%82%E4%BD%95%E7%BC%96%E5%86%99%E4%BD%A0%E8%87%AA%E5%B7%B1%E7%9A%84WindBot-AI
Wiki written in Chinese,Use google translator to learn it
